FROM songdongsheng/server-jre:stretch
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ADD  docker-setup.sh META_RDC.sql elasticsearch-5.6.8-with-plugins.tar.gz /opt/
#RUN  /opt/docker-setup.sh
CMD  ["/bin/bash"]
