# docker build -t songdongsheng/server-jre-8:centos7-8u144-20170823 .
# docker tag      songdongsheng/server-jre-8:centos7-8u144-20170823 songdongsheng/server-jre-8:latest

FROM scratch
ADD  rootfs_centos7_server-jre-8u144-linux-x64.yum.tar.xz /
CMD  ["/bin/bash"]
